name: my_project
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  iconsax: ^0.0.8
  http: ^1.4.0
  provider: ^6.1.5
  auto_size_text: ^3.0.0 


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0


flutter:

  
  uses-material-design: true

  assets:
  - assets/images/google.png
  - assets/images/facebook.png
  - assets/images/breakfast.png
  - assets/images/lunch.png
  - assets/images/evening.png
  - assets/images/dinner.png
  - assets/images/desert.png
  - assets/images/juice.png
  - assets/images/chef.png
  - assets/images/forgot.png
  - assets/images/app_logo.png